type SoftwareVersion = `${number}.${number}.${number}(${string})`;

export type HilinkApiResponse = {
	StateLogin: {
		userlevel: string;
		firstlogin: string;
		remainwaittime: string;
		rsapadingtype: string;
		State: string;
		wifipwdsamewithwebpwd: string;
		extern_password_type: string;
		accounts_number: string;
		username: string;
		password_type: string;
		history_login_flag: string;
		lockstatus: string;
	};
	TempToken: {
		token: string;
	};
	BaseTokens: {
		TokInfo: string;
		SesInfo: string;
	};
	Status: {
		ConnectionStatus: string;
		WifiConnectionStatus: string;
		SignalStrength: string;
		SignalIcon: string;
		CurrentNetworkType: string;
		CurrentServiceDomain: string;
		RoamingStatus: string;
		BatteryStatus: string;
		BatteryLevel: string;
		BatteryPercent: string;
		simlockStatus: string;
		PrimaryDns: string;
		SecondaryDns: string;
		PrimaryIPv6Dns: string;
		SecondaryIPv6Dns: string;
		CurrentWifiUser: string;
		TotalWifiUser: string;
		currenttotalwifiuser: string;
		ServiceStatus: string;
		SimStatus: string;
		WifiStatus: string;
		CurrentNetworkTypeEx: string;
		WanPolicy: string;
		maxsignal: string;
		wifiindooronly: string;
		wififrequence: string;
		classify: string;
		flymode: string;
		cellroam: string;
		dfsstatus: string;
		channelselection: string;
		batterydisplay: string;
		currentnetworkstring: string;
		usbup: string;
		wifiswitchstatus: string;
		bluetooth_edr_switch: string;
		bluetooth_edr_currert_user: string;
		hvdcp_online: string;
	};
	BasicInformation: {
		productfamily: string;
		classify: string;
		multimode: number;
		restore_default_status: number;
		sim_save_pin_enable: number;
		devicename: string;
		softwareversion: SoftwareVersion;
		SoftwareVersion: SoftwareVersion;
		WebUIVersion: SoftwareVersion;
		spreadname_en: string;
		spreadname_zh: string;
	};
	Information: {
		DeviceName: string;
		SerialNumber: string;
		Imei: number;
		Imsi: number;
		Iccid: string;
		Msisdn: string;
		HardwareVersion: string;
		SoftwareVersion: string;
		WebUIVersion: string;
		MacAddress1: string;
		MacAddress2: string;
		WanIPAddress: string;
		wan_dns_address: string;
		WanIPv6Address: string;
		wan_ipv6_dns_address: string;
		ProductFamily: string;
		Classify: string;
		supportmode: string;
		workmode: string;
		submask: string;
		BTMacAddress: string;
		Mccmnc: number;
		uptime: number;
		ImeiSvn: number;
		WifiMacAddrWl0: string;
		WifiMacAddrWl1: string;
		spreadname_en: string;
		spreadname_zh: string;
	};
	TrafficStatistics: {
		CurrentConnectTime: number;
		CurrentUpload: number;
		CurrentDownload: number;
		CurrentDownloadRate: number;
		CurrentUploadRate: number;
		TotalUpload: number;
		TotalDownload: number;
		TotalConnectTime: number;
		showtraffic: number;
	};
	UsbTethering: {
		tetheringswitch: number;
	};
};
